### ISSUE TITLE
Please update for the nexus

### ISSUE THREAD

**Issue by frodo19** [kodi-community-addons/script.skin.helper.colorpicker#17]
2022-11-16 12:54:24.791 T:13048   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\standard\AppData\Roaming\Kodi\addons\script.skin.helper.colorpicker\default.py", line 7, in <module>
                                                       import resources.lib.ColorPicker as cp
                                                     File "C:\Users\standard\AppData\Roaming\Kodi\addons\script.skin.helper.colorpicker\resources\lib\ColorPicker.py", line 15, in <module>
                                                       COLORFILES_PATH = xbmc.translatePath("special://profile/addon_data/%s/colors/" % ADDON_ID)
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

Solution: 
script.skin.helper.colorpicker\resources\lib\ColorPicker.py

replace lines 15, 16, and 17 with

COLORFILES_PATH = xbmcvfs.translatePath("special://profile/addon_data/%s/colors/" % ADDON_ID)
SKINCOLORFILES_PATH = xbmcvfs.translatePath("special://profile/addon_data/%s/colors/" % xbmc.getSkinDir())
SKINCOLORFILE = xbmcvfs.translatePath("special://skin/extras/colors/colors.xml")

only need to change xbmc.translatePath to xbmcfvs.translatePath, will solve.

**Comment by frodo19** [comment]
ignore
